### PR TITLE
Update install instruction add testpypi section to Developer Guide

### PR DESCRIPTION
**Pull request by DamonLee5**

### CODE REVIEW

**Comment by cabouman** [comment]
Wenrui, can you give me some description of what these changes do?

Also, have you throughly tested the changes?

**Comment by DamonLee5** [comment]
> Wenrui, can you give me some description of what these changes do?
> 
> Also, have you throughly tested the changes?

I only updated the install instruction. Now, we don't need to install the environment with environment.yml. Pypi does not use conda to set up environment, so I try to avoid using environment.yml. Brendt's repo doesn't use environment.yml too.

Now, we can create a clean virtual environment and directly use requirements.txt to set up the svmbir environment. I tested it on different platforms and it works.

Also, I added some instructions on testpypi for the developer, including some websites.

**Comment by sjkisner** [comment]
After creating and activating the empty environment,
`pip install -r requirements.txt`
gave me this error:

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
traitlets 4.3.3 requires decorator, which is not installed.
jupyter-client 6.1.6 requires tornado>=4.1, which is not installed.
ipykernel 5.3.4 requires ipython>=5.0.0, which is not installed.
ipykernel 5.3.4 requires tornado>=4.2, which is not installed.

I could still install and run svmbir though.

**Comment by cabouman** [comment]
Wenrui, do you want to resolve these issues the Jordan raised, and then I can merge your modified pull request.

**Comment by DamonLee5** [comment]
> After creating and activating the empty environment,
> `pip install -r requirements.txt`
> gave me this error:
> 
> ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
> traitlets 4.3.3 requires decorator, which is not installed.
> jupyter-client 6.1.6 requires tornado>=4.1, which is not installed.
> ipykernel 5.3.4 requires ipython>=5.0.0, which is not installed.
> ipykernel 5.3.4 requires tornado>=4.2, which is not installed.
> 
> I could still install and run svmbir though.

Those package are not required by svmbir. 
pip install -r requirements.txt already installs required packages. Therefore, we can still install and run svmbir successfully. 

For the pip's dependency resolver error, I guess you will need to install other packages to make sure that Jupyter Notebook can work when you create a clean environment.

**Comment by DamonLee5** [comment]
> Wenrui, do you want to resolve these issues the Jordan raised, and then I can merge your modified pull request.

Sure, I will find out the reason for this issue.

**Comment by sjkisner** [comment]
Whatever is causing that error message about jupyter and ipykernel dependencies seems to be specific to my environment.  It doesn't prevent svmbir from installing, so maybe it's fine to go with either (or both) of these alternatives for setting up the environment:

```
conda create -n smbir python=3.8
conda activate svmbir
pip install -r requirements.txt
```
or
```
conda env create -f environment.yml
conda activate svmbir
```

**Review by sjkisner — APPROVED** [review]

**Pull request merged**
