### PR TITLE
_sino_indicator fix for issue  #221

### PR DESCRIPTION
**Pull request by cabouman**

### CODE REVIEW

**Review by dyang37 — APPROVED** [review]
Tested on my end with 3D shepp Logan Demo script.
Tested the following three cases, and reconstruction works well in all of them:
1. original 3D shepp Logan demo
2. Set one entry of sinogram to be np.nan
3. Set one entry of sinogram to be np.inf.

**Comment by dyang37** [comment]
Actually this might still not be the complete fix. For the test case where an entire detector row of the sinogram is set to `nan` this gives me `nan` in the reconstruction:

```
auto sigma_y = 1.00000, auto sigma_prior = nan
Reconstructing axial size (rows,cols)=(256,256).
Found system matrix: /home/yang1467/.cache/svmbir/sysmatrix/bc0b0940eb4abd0cc86e.2Dsvmatrix
Reading system matrix...
Projecting image...
Reconstructing...
	iteration 1, average change nan %
	iteration 2, average change nan %
	iteration 3, average change nan %
	iteration 4, average change nan %
	iteration 5, average change nan %
	iteration 6, average change nan %
	iteration 7, average change nan %
	iteration 8, average change nan %
	iteration 9, average change nan %
	iteration 10, average change nan %
	iteration 11, average change nan %
	iteration 12, average change nan %
	iteration 13, average change nan %
	iteration 14, average change nan %
```

This can be reproduced by adding the following code at line 39 of 3D shepp-logan demo script:
```
# put one point of sino to be nan
sino[:,num_slices-1,:] = np.nan

weights = svmbir.calc_weights(sino, weight_type='unweighted')
# set weights associated with invalid sino entries to be 0
weights[np.isfinite(sino)==0] = 0.
sigma_y = svmbir.auto_sigma_y(sino, weights=weights, snr_db=snr_db)
sigma_prior = svmbir.auto_sigma_prior(sino, sharpness=sharpness)
# print out auto sigma values
print(f"auto sigma_y = {sigma_y:.5f}, auto sigma_prior = {sigma_prior:.5f}")
```

**Comment by dyang37** [comment]
One problem, although not the root cause of the nan updates we are seeing here, is that the calculated sigma_prior in this case is nan:
```
auto sigma_y = 1.00000, auto sigma_prior = nan
```

This is because of the following line of code at line 198 of svmbir.py:
```
    typical_img_value = np.average(sino, weights=sino_indicator) / (num_channels * delta_channel)
```

Even under the case where the weights corresponding to "bad" sino entries are set to 0, the weighted average of np.average(sino, weights=sino_indicator) is still nan, since in python `nan*0=nan` and `inf*0=nan`.

Therefore I propose that we make the following change:
`typical_img_value = np.average(sino[np.isfinite(sino)], weights=sino_indicator[np.isfinite(sino)]) / (num_channels * delta_channel)`


After making this update the nan problem of sigma_prior goes away, but the nan in the reconstruction updates still preserve:
```
auto sigma_y = 1.00000, auto sigma_prior = 0.58506
Reconstructing axial size (rows,cols)=(256,256).
Found system matrix: /home/yang1467/.cache/svmbir/sysmatrix/bc0b0940eb4abd0cc86e.2Dsvmatrix
Reading system matrix...
Projecting image...
Reconstructing...
	iteration 1, average change nan %
	iteration 2, average change nan %
	iteration 3, average change nan %
	iteration 4, average change nan %
	iteration 5, average change nan %
	iteration 6, average change nan %
	iteration 7, average change nan %
	iteration 8, average change nan %
	iteration 9, average change nan %
	iteration 10, average change nan %
	iteration 11, average change nan %
	iteration 12, average change nan %
	iteration 13, average change nan %
	iteration 14, average change nan %
	iteration 15, average change nan %
	iteration 16, average change nan %
	iteration 17, average change nan %
	iteration 18, average change nan %
	iteration 19, average change nan %
	iteration 20, average change nan %
	iteration 21, average change nan %
```
We might need to do some more digging regarding this.

**Review by sjkisner — APPROVED** [review]

**Comment by sjkisner** [comment]
Something that's a little strange about this fix is it looks like the _sino_indicator() function is accommodating a sinogram input with NaN values, but I don't believe we're addressing that anywhere else.  We should either raise an exception for this case, or do some corrections like removing the infinite values from the sinogram and giving them zero weight.

**Comment by cabouman** [comment]
Maybe we can discuss this issue, and decided how to best handle it.

**Comment by dyang37** [comment]
As briefly discussed in ORNL meeting earlier today, one way to do this is that whenever NaN is detected, we set both the sinogram entry and corresponding weights entry to be 0, so that the NaN entry will get ignored when doing reconstruction.

**Comment by dyang37** [comment]
> As briefly discussed in ORNL meeting earlier today, one way to do this is that whenever NaN is detected, we set both the sinogram entry and corresponding weights entry to be 0, so that the NaN entry will get ignored when doing reconstruction.

An alternative way is to replace the NaN entry with the median value of its neighborhood (assuming NaN values are sparse).

**Pull request closed without merging**
