### PR TITLE
Move dictionaries from svmbir.py to _utils.py

### PR DESCRIPTION
**Pull request by DamonLee5**

### CODE REVIEW

**Review by smajee — CHANGES_REQUESTED** [review]
I think it would be better to manually set the default entries of reconparams in the recon function similar to how the sinoparams and imgparams dictionaries are set in _init_geometry.

This will remove the need for the _default_reconparams dictionary altogether.

**Comment by sjkisner** [comment]
Almost all of them are already set in recon().  I think the only that aren't are b_nearest and b_diag.

**Comment by DamonLee5** [comment]
And we can put map_pyconv2camelcase to _transform_pyconv2c.?

**Comment by DamonLee5** [comment]
> Almost all of them are already set in recon(). I think the only that aren't are b_nearest and b_diag.

Okay. So it set through parse_params() in recon().

**Comment by DamonLee5** [comment]
> Almost all of them are already set in recon(). I think the only that aren't are b_nearest and b_diag.

You are right, just

    'prior_model': 'QGGMRF'
    'b_nearest': 1.0,
    'b_diag': 0.707,
    'weight_type': 'unweighted'

aren't in recon().

**Comment by smajee** [comment]
You don't have to use parse_params(), just set the fields normally.

**Comment by DamonLee5** [comment]
> You don't have to use parse_params(), just set the fields normally.

Do you mean copy the entire default_reconparams definition under recon()?

**Comment by smajee** [comment]
@sjkisner can you please comment on whether weight_type should be set in recon_params with the current version of the c-code?

@DamonLee5 : no just set the four fields that are not being set.

**Comment by cabouman** [comment]
Based on the conversation, it sounds like we need to rethink these proposed changes. We need to make the code as simple and clean as possible. BTW, I made the fix on the test parameters.

**Pull request closed without merging**
