### PR TITLE
Raise error when p<=0.

### PR DESCRIPTION
**Pull request by DamonLee5**

### CODE REVIEW

**Comment by cabouman** [comment]
Sorry, maybe I'm wrong. If Jordan thinks the code works for p=0, then we should allow that.

**Comment by DamonLee5** [comment]
> Sorry, maybe I'm wrong. If Jordan thinks the code works for p=0, then we should allow that.

Jordan asked do we want p in the range [1,2]. Maybe I should wait for his comment before I making another change.

**Review by smajee — CHANGES_REQUESTED** [review]
Perhaps we could change it to something like 
`raise ValueError('Parameter p({}) is outside the allowed range'.format(p))`

The range can also be added to the msg.
This way the user knows what is the value of p and why it is throwing an exception.

**Comment by sjkisner** [comment]
I think generally we want  1<=p<=q<=2 , correct?

**Comment by cabouman** [comment]
Wenrui, you need to test the values of `p` and `q` together because then need to meet the joint constraint that `1<=p<=q<=2`.

So I think you need something like:

``
If p<1 : p=1
else : 
	if q>2 : q=2
	else : if p>q : p=q
``

**Comment by smajee** [comment]
I think there should be three different exception handling: for the range of p, for the range of q, and for relative values of p and q.
This will result in cleaner code than handling the constraints in a single exception handling.

The exception messages should contain the value of the parameter and the expected range. 
For the comparison between p and q, the message should contain values of p and q.

**Pull request closed without merging**
