### PR TITLE
Completed missions listed in svmbir plans.

### PR DESCRIPTION
**Pull request by DamonLee5**
I completed some tasks listed in svmbir plan in my branch. More details can read the email I sent last night.

Here is the link to svmbir plan,
https://docs.google.com/document/d/10AEXVLPu6d6SJPyJ8LGTCY0Ag4ou1v0iZA1be397-Tg/edit

- Clean the setup.py file to replace duplicated strings with definitions at the top of the file.

- Move ruamel.yaml dependencies to interface_py_c.py
All ruamel.yaml dependencies are mbir read/modify Param Files, so I move both of them to interface_py_c.py. 

- Move plotting part of phantom.py to demo folder.

- Include requirements_demo.txt in demo folder:  needs matplotlib
I moved plot_image function, which needs matplotlib, to demo_utils.py in demo. 
Each demo files import plot_image from demo_utils.py. 
Also, I moved matplotlib to requirements_demo.txt from requirements.txt in root folder.

### CODE REVIEW

**Comment by DamonLee5** [comment]
For the testing, I tested both the Cython interface and the command-line interface on my Mac. 
If anyone meets some issues, please give me feedback, then I can try to fix them.

**Review by smajee — CHANGES_REQUESTED** [review]
It is good that some of the functions specific to the command line interface are now moved to the interface_py_c file.
However, there are still some functions in utils (such as read_sino_openmbir) that are specific to the command line interface and should be moved to interface_py_c.py

Otherwise, it looks good to me.

**Comment by DamonLee5** [comment]
> It is good that some of the functions specific to the command line interface are now moved to the interface_py_c file.
> However, there are still some functions in utils (such as read_sino_openmbir) that are specific to the command line interface and should be moved to interface_py_c.py
> 
> Otherwise, it looks good to me.

Do you mean those mbir read/write/delete Binary Files?

**Comment by smajee** [comment]
> > It is good that some of the functions specific to the command line interface are now moved to the interface_py_c file.
> > However, there are still some functions in utils (such as read_sino_openmbir) that are specific to the command line interface and should be moved to interface_py_c.py
> > Otherwise, it looks good to me.
> 
> Do you mean those mbir read/write/delete Binary Files?

Yes, those mbir read/write/delete Binary Files are only used in the interface_py_c.py file.

**Comment by DamonLee5** [comment]
> > > It is good that some of the functions specific to the command line interface are now moved to the interface_py_c file.
> > > However, there are still some functions in utils (such as read_sino_openmbir) that are specific to the command line interface and should be moved to interface_py_c.py
> > > Otherwise, it looks good to me.
> > 
> > 
> > Do you mean those mbir read/write/delete Binary Files?
> 
> Yes, those mbir read/write/delete Binary Files are only used in the interface_py_c.py file.

I moved them to interface_py_c.py file.

**Review by smajee — APPROVED** [review]
Looks good to me.

**Comment by cabouman** [comment]
So what is the final conclusion on this pull request?
Has it been thoroughly tested?

**Review by sjkisner — APPROVED** [review]

**Pull request merged**
