### PR TITLE
modified default values for snr_db and magnification

### PR DESCRIPTION
**Pull request by dyang37**
This PR modifies the default `snr_db` from 30.0 to 40.0, and `magnification` from None to 1.0 in functions `recon()`, `project()`, and `backproject()`. Also, the checker for `magnification=None` is removed in these functions.

For the corner case where `magnification` of fan beam reconstruction mismatches the real magnification, we should simply get a reconstruction with a scaled intensity.

Tested this corner case with the fanbeam demo script. Passed in the default `magnification=1.0` for `recon()` function. The reconstruction looks identical as before, except that the display window changes from 1.0-1.2 to 0.5-0.6.

### CODE REVIEW

**Comment by cabouman** [comment]
This looks good to me. I also to the opportunity to change the default to `max_resolutions = 2` so that it defaults to multi resolution reconstruction.
My experience is that multi resolution reconstruction is uniformly better.

**Comment by sjkisner** [comment]
One exception is I wouldn't make multi-resolution the default if an initial condition is given.

**Comment by cabouman** [comment]
Jordan, very good point. I need to think about how to handle this. The code actually handles the case when there is an initial condition but `max_resolutions = 2 `, but it probably isn't what people would want or expect.

**Comment by sjkisner** [comment]
Right, for example if you want to run more iterations on an existing result you'd want to input the last image state and continue at full resolution. This is what I use the initial condition for more than anything.

**Comment by cabouman** [comment]
Jordan, I am thinking that I can create a function `auto_max_resolution(init_image, prox_image)` . Then if the init_image or proj_image are set as regular images, then it will set `max_resolutions =0`;
otherwise, it will set `max_resolutions =2`.

Does that seem reasonable to you?

**Comment by cabouman** [comment]
I merged the prerelease branch with `auto_param_fix` and resolved all the conflicts. I also made some additional updates, and I tested it with various demos.

So the `auto_param_fix` branch should now include:
- Includes all updates from `kisner/fan_flat`
- Changes default to `snr_db=40`
- Changes default to `max_resolutions=2` except when and initial image is provided

Everyone, please test and give feedback.

**Comment by dyang37** [comment]
> I merged the prerelease branch with `auto_param_fix` and resolved all the conflicts. I also made some additional updates, and I tested it with various demos.
> 
> So the `auto_param_fix` branch should now include:
> 
> * Includes all updates from `kisner/fan_flat`
> * Changes default to `snr_db=40`
> * Changes default to `max_resolutions=2` except when and initial image is provided
> 
> Everyone, please test and give feedback.

Tested with `demo_fanbeam.py` and everything looks good.

**Review by sjkisner — APPROVED** [review]

**Pull request merged**
